### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by 851682852** [godka/DCPPG#1]

**Comment by godka** [comment]
This is the simplest implementation of DCPPG (dual-clip phasic policy gradient), which can be viewed as the fusion of Dual-clip PPO + PPG. It significantly improves the converge speed compared with DCPPO.

DCPPG has been adopted in our previous work:
_Huang, Tianchi, et al. "Buffer awareness neural adaptive video streaming for avoiding extra buffer consumption." IEEE INFOCOM 2023-IEEE Conference on Computer Communications. IEEE, 2023._

**Comment by 851682852** [comment]
Can this method be applied to your other project 'pensieve-ppo' to replace the PPO method?

**Comment by godka** [comment]
yep, it can! let's see how it goes~
feel free to submit a pull request for pensieve-ppo
